### ISSUE TITLE
Permission Error when opening the web app of map2seq

### ISSUE THREAD

**Issue by procyontao** [jianglab/map2seq#9]
Hi,

I'm interested in using this web application; however, I've come across an error that's preventing me from proceeding. I was wondering if you could resolve this issue. Thank you!

PermissionError: [Errno 13] Permission denied: '/home/adminuser/venv/bin/libtbx.list_source_files_sorted_by_size'
Traceback:
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/mount/src/map2seq/streamlit_app.py", line 57, in <module>
    z.extractall(root_folder)
File "/usr/local/lib/python3.9/tarfile.py", line 2243, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
File "/usr/local/lib/python3.9/tarfile.py", line 2310, in _extract_one
    self._handle_fatal_error(e)
File "/usr/local/lib/python3.9/tarfile.py", line 2306, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
File "/usr/local/lib/python3.9/tarfile.py", line 2389, in _extract_member
    self.makefile(tarinfo, targetpath)
File "/usr/local/lib/python3.9/tarfile.py", line 2434, in makefile
    with bltn_open(targetpath, "wb") as target:

**Comment by xqzhang777** [comment]
> Hi,
> 
> I'm interested in using this web application; however, I've come across an error that's preventing me from proceeding. I was wondering if you could resolve this issue. Thank you!
> 
> PermissionError: [Errno 13] Permission denied: '/home/adminuser/venv/bin/libtbx.list_source_files_sorted_by_size' Traceback: File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/mount/src/map2seq/streamlit_app.py", line 57, in z.extractall(root_folder) File "/usr/local/lib/python3.9/tarfile.py", line 2243, in extractall self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(), File "/usr/local/lib/python3.9/tarfile.py", line 2310, in _extract_one self._handle_fatal_error(e) File "/usr/local/lib/python3.9/tarfile.py", line 2306, in _extract_one self._extract_member(tarinfo, os.path.join(path, tarinfo.name), File "/usr/local/lib/python3.9/tarfile.py", line 2389, in _extract_member self.makefile(tarinfo, targetpath) File "/usr/local/lib/python3.9/tarfile.py", line 2434, in makefile with bltn_open(targetpath, "wb") as target:

Hi procyontao,

Thanks for reporting this issue. It seems the Streamlit Cloud has made some changes to the read-write permissions to the app's working directories which interfered with the way we dealt with some dependencies. We are looking into this now.

**Comment by xqzhang777** [comment]
> Hi,
> 
> I'm interested in using this web application; however, I've come across an error that's preventing me from proceeding. I was wondering if you could resolve this issue. Thank you!
> 
> PermissionError: [Errno 13] Permission denied: '/home/adminuser/venv/bin/libtbx.list_source_files_sorted_by_size' Traceback: File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script exec(code, module.**dict**) File "/mount/src/map2seq/streamlit_app.py", line 57, in z.extractall(root_folder) File "/usr/local/lib/python3.9/tarfile.py", line 2243, in extractall self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(), File "/usr/local/lib/python3.9/tarfile.py", line 2310, in _extract_one self._handle_fatal_error(e) File "/usr/local/lib/python3.9/tarfile.py", line 2306, in _extract_one self._extract_member(tarinfo, os.path.join(path, tarinfo.name), File "/usr/local/lib/python3.9/tarfile.py", line 2389, in _extract_member self.makefile(tarinfo, targetpath) File "/usr/local/lib/python3.9/tarfile.py", line 2434, in makefile with bltn_open(targetpath, "wb") as target:

Hi procyontao,

This issue has been fixed with the recent update. The web application is back online now.
